FROM php:8.2.0-apache
COPY ./back /var/www/html
ENV DB_HOST=mysql_server:3306
ENV DB_Name=part1
ENV DB_User=root
ENV DB_Password=admin

EXPOSE 80
# Installation de l'extension MySQLi
RUN docker-php-ext-install mysqli